version: '3.8'

services:

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - ./server:/app   

  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    # depends_on:
    #   - api
    volumes:
      - ./client:/app
    ports:
      - 3000:3000
